CREATE TABLE USER (
	username TEXT PRIMARY KEY,
	passwd TEXT NOT NULL,
	ctTime TEXT NOT NULL,
	category TEXT NOT NULL
);

CREATE TABLE CATEGORY (
	catg_name TEXT PRIMARY KEY,
	max_time INT DEFAULT 0
);

CREATE TABLE BLOCKLIST (
	catg TEXT NOT NULL,
	listname TEXT NOT NULL,
	url TEXT NOT NULL,
	FOREIGN KEY catg REFERENCES CATEGORY(catg_name) 
);
